/*
 * AUTOGENERATED FILE. DO NOT EDIT IT
 * Generated by "generate_jsb.py -c cocos2d_jsb.ini" on 2013-03-10
 * Script version: v0.6
 */

namespace cc {
  // TODO
  // cc.Sprite.INDEX_NOT_INITIALIZED = -1;
  export const TMX_ORIENTATION_HEX = 0x1;
  export const TMX_ORIENTATION_ISO = 0x2;
  export const TMX_ORIENTATION_ORTHO = 0x0;
  export const Z_COMPRESSION_BZIP2 = 0x1;
  export const Z_COMPRESSION_GZIP = 0x2;
  export const Z_COMPRESSION_NONE = 0x3;
  export const Z_COMPRESSION_ZLIB = 0x0;
  /**
   * default gl blend src function. Compatible with premultiplied alpha images.
   * @constant
   * @type Number
   */
  // cc.BLEND_SRC = cc.OPTIMIZE_BLEND_FUNC_FOR_PREMULTIPLIED_ALPHA ? 1 : 0x0302;
  export const BLEND_DST = 0x303;
  /**
   * default gl blend dst function. Compatible with premultiplied alpha images.
   * @constant
   * @type Number
   */
  export const BLEND_SRC = 0x1;
  export const DIRECTOR_IOS_USE_BACKGROUND_THREAD = 0x0;
  export const DIRECTOR_MAC_THREAD = 0x0;
  export const DIRECTOR_STATS_INTERVAL = 0.1;
  export const ENABLE_BOX2_D_INTEGRATION = 0x0;
  export const ENABLE_DEPRECATED = 0x1;
  export const ENABLE_GL_STATE_CACHE = 0x1;
  export const ENABLE_PROFILERS = 0x0;
  export const ENABLE_STACKABLE_ACTIONS = 0x1;
  export const FIX_ARTIFACTS_BY_STRECHING_TEXEL = 0x0;
  export const GL_ALL = 0x0;
  export const LABELATLAS_DEBUG_DRAW = 0x0;
  export const LABELBMFONT_DEBUG_DRAW = 0x0;
  export const MAC_USE_DISPLAY_LINK_THREAD = 0x0;
  export const MAC_USE_MAIN_THREAD = 0x2;
  export const MAC_USE_OWN_THREAD = 0x1;
  export const NODE_RENDER_SUBPIXEL = 0x1;
  export const PVRMIPMAP_MAX = 0x10;
  export const SPRITEBATCHNODE_RENDER_SUBPIXEL = 0x1;
  export const SPRITE_DEBUG_DRAW = 0x0;
  export const TEXTURE_ATLAS_USE_TRIANGLE_STRIP = 0x0;
  export const TEXTURE_ATLAS_USE_VAO = 0x1;
  export const USE_L_A88_LABELS = 0x1;
  export const ACTION_TAG_INVALID = -1;
  export const DEVICE_MAC = 0x6;
  export const DEVICE_MAC_RETINA_DISPLAY = 0x7;
  export const DEVICEI_PAD = 0x4;
  export const DEVICEI_PAD_RETINA_DISPLAY = 0x5;
  export const DEVICEI_PHONE = 0x0;
  export const DEVICEI_PHONE5 = 0x2;
  export const DEVICEI_PHONE5_RETINA_DISPLAY = 0x3;
  export const DEVICEI_PHONE_RETINA_DISPLAY = 0x1;
  export const FILE_UTILS_SEARCH_DIRECTORY_MODE = 0x1;
  export const FILE_UTILS_SEARCH_SUFFIX_MODE = 0x0;
  export const FLIPED_ALL = 0xe0000000;
  export const FLIPPED_MASK = 0x1fffffff;
  export const IMAGE_FORMAT_JPEG = 0x0;
  export const IMAGE_FORMAT_PNG = 0x1;
  export const ITEM_SIZE = 0x20;
  export const LABEL_AUTOMATIC_WIDTH = -1;
  export const LINE_BREAK_MODE_CHARACTER_WRAP = 0x1;
  export const LINE_BREAK_MODE_CLIP = 0x2;
  export const LINE_BREAK_MODE_HEAD_TRUNCATION = 0x3;
  export const LINE_BREAK_MODE_MIDDLE_TRUNCATION = 0x5;
  export const LINE_BREAK_MODE_TAIL_TRUNCATION = 0x4;
  export const LINE_BREAK_MODE_WORD_WRAP = 0x0;
  export const MAC_VERSION_10_6 = 0xa060000;
  export const MAC_VERSION_10_7 = 0xa070000;
  export const MAC_VERSION_10_8 = 0xa080000;
  export const MENU_HANDLER_PRIORITY = -128;
  export const MENU_STATE_TRACKING_TOUCH = 0x1;
  export const MENU_STATE_WAITING = 0x0;
  export const NODE_TAG_INVALID = -1;

  // TODO
  // cc.ParticleSystem.TYPE_FREE = 0;
  // cc.ParticleSystem.TYPE_RELATIVE = 1;
  // cc.ParticleSystem.TYPE_GROUPED = 2;
  // cc.ParticleSystem.DURATION_INFINITY = -1;
  // cc.ParticleSystem.MODE_GRAVITY = 0;
  // cc.ParticleSystem.MODE_RADIUS = 1;
  // cc.ParticleSystem.START_SIZE_EQUAL_TO_END_SIZE = -1;
  // cc.ParticleSystem.START_RADIUS_EQUAL_TO_END_RADIUS = -1;

  export const PRIORITY_NON_SYSTEM_MIN = -2147483647;
  // TODO
  // cc.ProgressTimer.TYPE_BAR = 0x1;
  // cc.ProgressTimer.TYPE_RADIAL = 0x0;
  export const RESOLUTION_MAC = 0x1;
  export const RESOLUTION_MAC_RETINA_DISPLAY = 0x2;
  export const RESOLUTION_UNKNOWN = 0x0;
  export const TMX_TILE_DIAGONAL_FLAG = 0x20000000;
  export const TMX_TILE_HORIZONTAL_FLAG = 0x80000000;
  export const TMX_TILE_VERTICAL_FLAG = 0x40000000;

  export const TEXT_ALIGNMENT_CENTER = 1;
  export const TEXT_ALIGNMENT_RIGHT = 2;
  export const TEXT_ALIGNMENT_LEFT = 0;

  export const TOUCHES_ALL_AT_ONCE = 0x0;
  export const TOUCHES_ONE_BY_ONE = 0x1;
  export const TRANSITION_ORIENTATION_DOWN_OVER = 0x1;
  export const TRANSITION_ORIENTATION_LEFT_OVER = 0x0;
  export const TRANSITION_ORIENTATION_RIGHT_OVER = 0x1;
  export const TRANSITION_ORIENTATION_UP_OVER = 0x0;
  export const UNIFORM_COS_TIME = 0x5;
  export const UNIFORM_MV_MATRIX = 0x1;
  export const UNIFORM_MVP_MATRIX = 0x2;
  export const UNIFORM_P_MATRIX = 0x0;
  export const UNIFORM_RANDOM01 = 0x6;
  export const UNIFORM_SAMPLER = 0x7;
  export const UNIFORM_SIN_TIME = 0x4;
  export const UNIFORM_TIME = 0x3;
  export const UNIFORM_MAX = 0x8;
  export const VERTICAL_TEXT_ALIGNMENT_BOTTOM = 0x2;
  export const VERTICAL_TEXT_ALIGNMENT_CENTER = 0x1;
  export const VERTICAL_TEXT_ALIGNMENT_TOP = 0x0;
  export const OS_VERSION_4_0 = 0x4000000;
  export const OS_VERSION_4_0_1 = 0x4000100;
  export const OS_VERSION_4_1 = 0x4010000;
  export const OS_VERSION_4_2 = 0x4020000;
  export const OS_VERSION_4_2_1 = 0x4020100;
  export const OS_VERSION_4_3 = 0x4030000;
  export const OS_VERSION_4_3_1 = 0x4030100;
  export const OS_VERSION_4_3_2 = 0x4030200;
  export const OS_VERSION_4_3_3 = 0x4030300;
  export const OS_VERSION_4_3_4 = 0x4030400;
  export const OS_VERSION_4_3_5 = 0x4030500;
  export const OS_VERSION_5_0 = 0x5000000;
  export const OS_VERSION_5_0_1 = 0x5000100;
  export const OS_VERSION_5_1_0 = 0x5010000;
  export const OS_VERSION_6_0_0 = 0x6000000;
  export const ANIMATION_FRAME_DISPLAYED_NOTIFICATION =
    "CCAnimationFrameDisplayedNotification";
  export const CHIPMUNK_IMPORT = "chipmunk.h";
  export const ATTRIBUTE_NAME_COLOR = "a_color";
  export const ATTRIBUTE_NAME_POSITION = "a_position";
  export const ATTRIBUTE_NAME_TEX_COORD = "a_texCoord";
  export const ATTRIBUTE_NAME_TEX_COORD1 = "a_texCoord1";
  export const ATTRIBUTE_NAME_TEX_COORD2 = "a_texCoord2";
  export const ATTRIBUTE_NAME_TEX_COORD3 = "a_texCoord3";
  export const ATTRIBUTE_NAME_NORMAL = "a_normal";
  export const ATTRIBUTE_NAME_BLEND_WEIGHT = "a_blendWeight";
  export const ATTRIBUTE_NAME_BLEND_INDEX = "a_blendIndex";
}
