
// extern JSClass  *jsb_cocos2d_Label_class;
// extern JSObject *jsb_cocos2d_Label_prototype;

// bool js_cocos2dx_Label_constructor(JSContext *cx, uint32_t argc, jsval *vp);
// void js_cocos2dx_Label_finalize(JSContext *cx, JSObject *obj);
// void js_register_cocos2dx_Label(JSContext *cx, JS::HandleObject global);
// void register_all_cocos2dx(JSContext* cx, JS::HandleObject obj);
// bool js_cocos2dx_Label_isClipMarginEnabled(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_enableShadow(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_setDimensions(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getWidth(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getString(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getHeight(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_disableEffect(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getLabelType(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getTextColor(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getBlendFunc(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_enableWrap(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_setWidth(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getAdditionalKerning(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getBMFontSize(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getMaxLineWidth(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getHorizontalAlignment(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getShadowOffset(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getLineSpacing(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_setClipMarginEnabled(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_setString(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_setSystemFontName(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_isWrapEnabled(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getOutlineSize(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_setBMFontFilePath(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_initWithTTF(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_setLineHeight(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_setSystemFontSize(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_setOverflow(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_enableStrikethrough(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_updateContent(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getStringLength(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_setLineBreakWithoutSpace(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getStringNumLines(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_enableOutline(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getShadowBlurRadius(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getEffectColor(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_removeAllChildrenWithCleanup(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_setCharMap(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getDimensions(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_setMaxLineWidth(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getSystemFontName(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_setVerticalAlignment(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_setLineSpacing(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getRenderingFontSize(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getLineHeight(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getShadowColor(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getTTFConfig(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_enableItalics(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_setTextColor(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getLetter(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_setHeight(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_isShadowEnabled(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_enableGlow(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getOverflow(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getVerticalAlignment(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_setAdditionalKerning(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getSystemFontSize(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_setBlendFunc(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getTextAlignment(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getBMFontFilePath(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_setHorizontalAlignment(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_enableBold(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_enableUnderline(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_getLabelEffectType(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_setAlignment(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_requestSystemFontRefresh(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_setBMFontSize(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_createWithBMFont(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_create(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_createWithCharMap(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_createWithSystemFont(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_Label_Label(JSContext *cx, uint32_t argc, jsval *vp);

// extern JSClass  *jsb_cocos2d_LabelAtlas_class;
// extern JSObject *jsb_cocos2d_LabelAtlas_prototype;

// bool js_cocos2dx_LabelAtlas_constructor(JSContext *cx, uint32_t argc, jsval *vp);
// void js_cocos2dx_LabelAtlas_finalize(JSContext *cx, JSObject *obj);
// void js_register_cocos2dx_LabelAtlas(JSContext *cx, JS::HandleObject global);
// void register_all_cocos2dx(JSContext* cx, JS::HandleObject obj);
// bool js_cocos2dx_LabelAtlas_setString(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelAtlas_initWithString(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelAtlas_getString(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelAtlas_create(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelAtlas_LabelAtlas(JSContext *cx, uint32_t argc, jsval *vp);

// extern JSClass  *jsb_cocos2d_LabelBMFont_class;
// extern JSObject *jsb_cocos2d_LabelBMFont_prototype;

// bool js_cocos2dx_LabelBMFont_constructor(JSContext *cx, uint32_t argc, jsval *vp);
// void js_cocos2dx_LabelBMFont_finalize(JSContext *cx, JSObject *obj);
// void js_register_cocos2dx_LabelBMFont(JSContext *cx, JS::HandleObject global);
// void register_all_cocos2dx(JSContext* cx, JS::HandleObject obj);
// bool js_cocos2dx_LabelBMFont_setLineBreakWithoutSpace(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelBMFont_getBlendFunc(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelBMFont_getLetter(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelBMFont_getString(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelBMFont_setBlendFunc(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelBMFont_setString(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelBMFont_initWithString(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelBMFont_getFntFile(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelBMFont_setFntFile(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelBMFont_setAlignment(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelBMFont_setWidth(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelBMFont_create(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelBMFont_LabelBMFont(JSContext *cx, uint32_t argc, jsval *vp);

// extern JSClass  *jsb_cocos2d_LabelTTF_class;
// extern JSObject *jsb_cocos2d_LabelTTF_prototype;

// bool js_cocos2dx_LabelTTF_constructor(JSContext *cx, uint32_t argc, jsval *vp);
// void js_cocos2dx_LabelTTF_finalize(JSContext *cx, JSObject *obj);
// void js_register_cocos2dx_LabelTTF(JSContext *cx, JS::HandleObject global);
// void register_all_cocos2dx(JSContext* cx, JS::HandleObject obj);
// bool js_cocos2dx_LabelTTF_enableShadow(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_setDimensions(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_getFontSize(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_getString(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_setFlippedY(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_setFlippedX(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_setTextDefinition(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_setFontName(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_getHorizontalAlignment(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_initWithStringAndTextDefinition(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_setString(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_initWithString(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_setFontFillColor(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_getBlendFunc(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_enableStroke(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_getDimensions(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_setVerticalAlignment(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_setFontSize(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_getVerticalAlignment(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_getTextDefinition(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_setBlendFunc(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_getFontName(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_setHorizontalAlignment(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_disableShadow(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_disableStroke(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_create(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_createWithFontDefinition(JSContext *cx, uint32_t argc, jsval *vp);
// bool js_cocos2dx_LabelTTF_LabelTTF(JSContext *cx, uint32_t argc, jsval *vp);