declare namespace gl {
  const GCCSO_SHADER_BINARY_FJ: number; // 0x9260
  const _3DC_XY_AMD: number; // 0x87fa
  const _3DC_X_AMD: number; // 0x87f9
  const ACTIVE_ATTRIBUTES: number; // 0x8b89
  const ACTIVE_ATTRIBUTE_MAX_LENGTH: number; // 0x8b8a
  const ACTIVE_PROGRAM_EXT: number; // 0x8259
  const ACTIVE_TEXTURE: number; // 0x84e0
  const ACTIVE_UNIFORMS: number; // 0x8b86
  const ACTIVE_UNIFORM_MAX_LENGTH: number; // 0x8b87
  const ALIASED_LINE_WIDTH_RANGE: number; // 0x846e
  const ALIASED_POINT_SIZE_RANGE: number; // 0x846d
  const ALL_COMPLETED_NV: number; // 0x84f2
  const ALL_SHADER_BITS_EXT: number; // 0xffffffff
  const ALPHA: number; // 0x1906
  const ALPHA16F_EXT: number; // 0x881c
  const ALPHA32F_EXT: number; // 0x8816
  const ALPHA8_EXT: number; // 0x803c
  const ALPHA8_OES: number; // 0x803c
  const ALPHA_BITS: number; // 0xd55
  const ALPHA_TEST_FUNC_QCOM: number; // 0xbc1
  const ALPHA_TEST_QCOM: number; // 0xbc0
  const ALPHA_TEST_REF_QCOM: number; // 0xbc2
  const ALREADY_SIGNALED_APPLE: number; // 0x911a
  const ALWAYS: number; // 0x207
  const AMD_compressed_3DC_texture: number; // 0x1
  const AMD_compressed_ATC_texture: number; // 0x1
  const AMD_performance_monitor: number; // 0x1
  const AMD_program_binary_Z400: number; // 0x1
  const ANGLE_depth_texture: number; // 0x1
  const ANGLE_framebuffer_blit: number; // 0x1
  const ANGLE_framebuffer_multisample: number; // 0x1
  const ANGLE_instanced_arrays: number; // 0x1
  const ANGLE_pack_reverse_row_order: number; // 0x1
  const ANGLE_program_binary: number; // 0x1
  const ANGLE_texture_compression_dxt3: number; // 0x1
  const ANGLE_texture_compression_dxt5: number; // 0x1
  const ANGLE_texture_usage: number; // 0x1
  const ANGLE_translated_shader_source: number; // 0x1
  const ANY_SAMPLES_PASSED_CONSERVATIVE_EXT: number; // 0x8d6a
  const ANY_SAMPLES_PASSED_EXT: number; // 0x8c2f
  const APPLE_copy_texture_levels: number; // 0x1
  const APPLE_framebuffer_multisample: number; // 0x1
  const APPLE_rgb_422: number; // 0x1
  const APPLE_sync: number; // 0x1
  const APPLE_texture_format_BGRA8888: number; // 0x1
  const APPLE_texture_max_level: number; // 0x1
  const ARM_mali_program_binary: number; // 0x1
  const ARM_mali_shader_binary: number; // 0x1
  const ARM_rgba8: number; // 0x1
  const ARRAY_BUFFER: number; // 0x8892
  const ARRAY_BUFFER_BINDING: number; // 0x8894
  const ATC_RGBA_EXPLICIT_ALPHA_AMD: number; // 0x8c93
  const ATC_RGBA_INTERPOLATED_ALPHA_AMD: number; // 0x87ee
  const ATC_RGB_AMD: number; // 0x8c92
  const ATTACHED_SHADERS: number; // 0x8b85
  const BACK: number; // 0x405
  const BGRA8_EXT: number; // 0x93a1
  const BGRA_EXT: number; // 0x80e1
  const BGRA_IMG: number; // 0x80e1
  const BINNING_CONTROL_HINT_QCOM: number; // 0x8fb0
  const BLEND: number; // 0xbe2
  const BLEND_COLOR: number; // 0x8005
  const BLEND_DST_ALPHA: number; // 0x80ca
  const BLEND_DST_RGB: number; // 0x80c8
  const BLEND_EQUATION: number; // 0x8009
  const BLEND_EQUATION_ALPHA: number; // 0x883d
  const BLEND_EQUATION_RGB: number; // 0x8009
  const BLEND_SRC_ALPHA: number; // 0x80cb
  const BLEND_SRC_RGB: number; // 0x80c9
  const BLUE_BITS: number; // 0xd54
  const BOOL: number; // 0x8b56
  const BOOL_VEC2: number; // 0x8b57
  const BOOL_VEC3: number; // 0x8b58
  const BOOL_VEC4: number; // 0x8b59
  const BUFFER: number; // 0x82e0
  const BUFFER_ACCESS_OES: number; // 0x88bb
  const BUFFER_MAPPED_OES: number; // 0x88bc
  const BUFFER_MAP_POINTER_OES: number; // 0x88bd
  const BUFFER_OBJECT_EXT: number; // 0x9151
  const BUFFER_SIZE: number; // 0x8764
  const BUFFER_USAGE: number; // 0x8765
  const BYTE: number; // 0x1400
  const CCW: number; // 0x901
  const CLAMP_TO_BORDER_NV: number; // 0x812d
  const CLAMP_TO_EDGE: number; // 0x812f
  const COLOR_ATTACHMENT0: number; // 0x8ce0
  const COLOR_ATTACHMENT0_NV: number; // 0x8ce0
  const COLOR_ATTACHMENT10_NV: number; // 0x8cea
  const COLOR_ATTACHMENT11_NV: number; // 0x8ceb
  const COLOR_ATTACHMENT12_NV: number; // 0x8cec
  const COLOR_ATTACHMENT13_NV: number; // 0x8ced
  const COLOR_ATTACHMENT14_NV: number; // 0x8cee
  const COLOR_ATTACHMENT15_NV: number; // 0x8cef
  const COLOR_ATTACHMENT1_NV: number; // 0x8ce1
  const COLOR_ATTACHMENT2_NV: number; // 0x8ce2
  const COLOR_ATTACHMENT3_NV: number; // 0x8ce3
  const COLOR_ATTACHMENT4_NV: number; // 0x8ce4
  const COLOR_ATTACHMENT5_NV: number; // 0x8ce5
  const COLOR_ATTACHMENT6_NV: number; // 0x8ce6
  const COLOR_ATTACHMENT7_NV: number; // 0x8ce7
  const COLOR_ATTACHMENT8_NV: number; // 0x8ce8
  const COLOR_ATTACHMENT9_NV: number; // 0x8ce9
  const COLOR_ATTACHMENT_EXT: number; // 0x90f0
  const COLOR_BUFFER_BIT: number; // 0x4000
  const COLOR_BUFFER_BIT0_QCOM: number; // 0x1
  const COLOR_BUFFER_BIT1_QCOM: number; // 0x2
  const COLOR_BUFFER_BIT2_QCOM: number; // 0x4
  const COLOR_BUFFER_BIT3_QCOM: number; // 0x8
  const COLOR_BUFFER_BIT4_QCOM: number; // 0x10
  const COLOR_BUFFER_BIT5_QCOM: number; // 0x20
  const COLOR_BUFFER_BIT6_QCOM: number; // 0x40
  const COLOR_BUFFER_BIT7_QCOM: number; // 0x80
  const COLOR_CLEAR_VALUE: number; // 0xc22
  const COLOR_EXT: number; // 0x1800
  const COLOR_WRITEMASK: number; // 0xc23
  const COMPARE_REF_TO_TEXTURE_EXT: number; // 0x884e
  const COMPILE_STATUS: number; // 0x8b81
  const COMPRESSED_RGBA_ASTC_10x10_KHR: number; // 0x93bb
  const COMPRESSED_RGBA_ASTC_10x5_KHR: number; // 0x93b8
  const COMPRESSED_RGBA_ASTC_10x6_KHR: number; // 0x93b9
  const COMPRESSED_RGBA_ASTC_10x8_KHR: number; // 0x93ba
  const COMPRESSED_RGBA_ASTC_12x10_KHR: number; // 0x93bc
  const COMPRESSED_RGBA_ASTC_12x12_KHR: number; // 0x93bd
  const COMPRESSED_RGBA_ASTC_4x4_KHR: number; // 0x93b0
  const COMPRESSED_RGBA_ASTC_5x4_KHR: number; // 0x93b1
  const COMPRESSED_RGBA_ASTC_5x5_KHR: number; // 0x93b2
  const COMPRESSED_RGBA_ASTC_6x5_KHR: number; // 0x93b3
  const COMPRESSED_RGBA_ASTC_6x6_KHR: number; // 0x93b4
  const COMPRESSED_RGBA_ASTC_8x5_KHR: number; // 0x93b5
  const COMPRESSED_RGBA_ASTC_8x6_KHR: number; // 0x93b6
  const COMPRESSED_RGBA_ASTC_8x8_KHR: number; // 0x93b7
  const COMPRESSED_RGBA_PVRTC_2BPPV1_IMG: number; // 0x8c03
  const COMPRESSED_RGBA_PVRTC_2BPPV2_IMG: number; // 0x9137
  const COMPRESSED_RGBA_PVRTC_4BPPV1_IMG: number; // 0x8c02
  const COMPRESSED_RGBA_PVRTC_4BPPV2_IMG: number; // 0x9138
  const COMPRESSED_RGBA_S3TC_DXT1_EXT: number; // 0x83f1
  const COMPRESSED_RGBA_S3TC_DXT3_ANGLE: number; // 0x83f2
  const COMPRESSED_RGBA_S3TC_DXT5_ANGLE: number; // 0x83f3
  const COMPRESSED_RGB_PVRTC_2BPPV1_IMG: number; // 0x8c01
  const COMPRESSED_RGB_PVRTC_4BPPV1_IMG: number; // 0x8c00
  const COMPRESSED_RGB_S3TC_DXT1_EXT: number; // 0x83f0
  const COMPRESSED_SRGB8_ALPHA8_ASTC_10x10_KHR: number; // 0x93db
  const COMPRESSED_SRGB8_ALPHA8_ASTC_10x5_KHR: number; // 0x93d8
  const COMPRESSED_SRGB8_ALPHA8_ASTC_10x6_KHR: number; // 0x93d9
  const COMPRESSED_SRGB8_ALPHA8_ASTC_10x8_KHR: number; // 0x93da
  const COMPRESSED_SRGB8_ALPHA8_ASTC_12x10_KHR: number; // 0x93dc
  const COMPRESSED_SRGB8_ALPHA8_ASTC_12x12_KHR: number; // 0x93dd
  const COMPRESSED_SRGB8_ALPHA8_ASTC_4x4_KHR: number; // 0x93d0
  const COMPRESSED_SRGB8_ALPHA8_ASTC_5x4_KHR: number; // 0x93d1
  const COMPRESSED_SRGB8_ALPHA8_ASTC_5x5_KHR: number; // 0x93d2
  const COMPRESSED_SRGB8_ALPHA8_ASTC_6x5_KHR: number; // 0x93d3
  const COMPRESSED_SRGB8_ALPHA8_ASTC_6x6_KHR: number; // 0x93d4
  const COMPRESSED_SRGB8_ALPHA8_ASTC_8x5_KHR: number; // 0x93d5
  const COMPRESSED_SRGB8_ALPHA8_ASTC_8x6_KHR: number; // 0x93d6
  const COMPRESSED_SRGB8_ALPHA8_ASTC_8x8_KHR: number; // 0x93d7
  const COMPRESSED_SRGB_ALPHA_S3TC_DXT1_NV: number; // 0x8c4d
  const COMPRESSED_SRGB_ALPHA_S3TC_DXT3_NV: number; // 0x8c4e
  const COMPRESSED_SRGB_ALPHA_S3TC_DXT5_NV: number; // 0x8c4f
  const COMPRESSED_SRGB_S3TC_DXT1_NV: number; // 0x8c4c
  const COMPRESSED_TEXTURE_FORMATS: number; // 0x86a3
  const CONDITION_SATISFIED_APPLE: number; // 0x911c
  const CONSTANT_ALPHA: number; // 0x8003
  const CONSTANT_COLOR: number; // 0x8001
  const CONTEXT_FLAG_DEBUG_BIT: number; // 0x2
  const CONTEXT_ROBUST_ACCESS_EXT: number; // 0x90f3
  const COUNTER_RANGE_AMD: number; // 0x8bc1
  const COUNTER_TYPE_AMD: number; // 0x8bc0
  const COVERAGE_ALL_FRAGMENTS_NV: number; // 0x8ed5
  const COVERAGE_ATTACHMENT_NV: number; // 0x8ed2
  const COVERAGE_AUTOMATIC_NV: number; // 0x8ed7
  const COVERAGE_BUFFERS_NV: number; // 0x8ed3
  const COVERAGE_BUFFER_BIT_NV: number; // 0x8000
  const COVERAGE_COMPONENT4_NV: number; // 0x8ed1
  const COVERAGE_COMPONENT_NV: number; // 0x8ed0
  const COVERAGE_EDGE_FRAGMENTS_NV: number; // 0x8ed6
  const COVERAGE_SAMPLES_NV: number; // 0x8ed4
  const CPU_OPTIMIZED_QCOM: number; // 0x8fb1
  const CULL_FACE: number; // 0xb44
  const CULL_FACE_MODE: number; // 0xb45
  const CURRENT_PROGRAM: number; // 0x8b8d
  const CURRENT_QUERY_EXT: number; // 0x8865
  const CURRENT_VERTEX_ATTRIB: number; // 0x8626
  const CW: number; // 0x900
  const DEBUG_CALLBACK_FUNCTION: number; // 0x8244
  const DEBUG_CALLBACK_USER_PARAM: number; // 0x8245
  const DEBUG_GROUP_STACK_DEPTH: number; // 0x826d
  const DEBUG_LOGGED_MESSAGES: number; // 0x9145
  const DEBUG_NEXT_LOGGED_MESSAGE_LENGTH: number; // 0x8243
  const DEBUG_OUTPUT: number; // 0x92e0
  const DEBUG_OUTPUT_SYNCHRONOUS: number; // 0x8242
  const DEBUG_SEVERITY_HIGH: number; // 0x9146
  const DEBUG_SEVERITY_LOW: number; // 0x9148
  const DEBUG_SEVERITY_MEDIUM: number; // 0x9147
  const DEBUG_SEVERITY_NOTIFICATION: number; // 0x826b
  const DEBUG_SOURCE_API: number; // 0x8246
  const DEBUG_SOURCE_APPLICATION: number; // 0x824a
  const DEBUG_SOURCE_OTHER: number; // 0x824b
  const DEBUG_SOURCE_SHADER_COMPILER: number; // 0x8248
  const DEBUG_SOURCE_THIRD_PARTY: number; // 0x8249
  const DEBUG_SOURCE_WINDOW_SYSTEM: number; // 0x8247
  const DEBUG_TYPE_DEPRECATED_BEHAVIOR: number; // 0x824d
  const DEBUG_TYPE_ERROR: number; // 0x824c
  const DEBUG_TYPE_MARKER: number; // 0x8268
  const DEBUG_TYPE_OTHER: number; // 0x8251
  const DEBUG_TYPE_PERFORMANCE: number; // 0x8250
  const DEBUG_TYPE_POP_GROUP: number; // 0x826a
  const DEBUG_TYPE_PORTABILITY: number; // 0x824f
  const DEBUG_TYPE_PUSH_GROUP: number; // 0x8269
  const DEBUG_TYPE_UNDEFINED_BEHAVIOR: number; // 0x824e
  const DECR: number; // 0x1e03
  const DECR_WRAP: number; // 0x8508
  const DELETE_STATUS: number; // 0x8b80
  const DEPTH24_STENCIL8_OES: number; // 0x88f0
  const DEPTH_ATTACHMENT: number; // 0x8d00
  const DEPTH_BITS: number; // 0xd56
  const DEPTH_BUFFER_BIT: number; // 0x100
  const DEPTH_BUFFER_BIT0_QCOM: number; // 0x100
  const DEPTH_BUFFER_BIT1_QCOM: number; // 0x200
  const DEPTH_BUFFER_BIT2_QCOM: number; // 0x400
  const DEPTH_BUFFER_BIT3_QCOM: number; // 0x800
  const DEPTH_BUFFER_BIT4_QCOM: number; // 0x1000
  const DEPTH_BUFFER_BIT5_QCOM: number; // 0x2000
  const DEPTH_BUFFER_BIT6_QCOM: number; // 0x4000
  const DEPTH_BUFFER_BIT7_QCOM: number; // 0x8000
  const DEPTH_CLEAR_VALUE: number; // 0xb73
  const DEPTH_COMPONENT: number; // 0x1902
  const DEPTH_COMPONENT16: number; // 0x81a5
  const DEPTH_COMPONENT16_NONLINEAR_NV: number; // 0x8e2c
  const DEPTH_COMPONENT16_OES: number; // 0x81a5
  const DEPTH_COMPONENT24_OES: number; // 0x81a6
  const DEPTH_COMPONENT32_OES: number; // 0x81a7
  const DEPTH_EXT: number; // 0x1801
  const DEPTH_FUNC: number; // 0xb74
  const DEPTH_RANGE: number; // 0xb70
  const DEPTH_STENCIL_OES: number; // 0x84f9
  const DEPTH_TEST: number; // 0xb71
  const DEPTH_WRITEMASK: number; // 0xb72
  const DITHER: number; // 0xbd0
  const DMP_shader_binary: number; // 0x1
  const DONT_CARE: number; // 0x1100
  const DRAW_BUFFER0_NV: number; // 0x8825
  const DRAW_BUFFER10_NV: number; // 0x882f
  const DRAW_BUFFER11_NV: number; // 0x8830
  const DRAW_BUFFER12_NV: number; // 0x8831
  const DRAW_BUFFER13_NV: number; // 0x8832
  const DRAW_BUFFER14_NV: number; // 0x8833
  const DRAW_BUFFER15_NV: number; // 0x8834
  const DRAW_BUFFER1_NV: number; // 0x8826
  const DRAW_BUFFER2_NV: number; // 0x8827
  const DRAW_BUFFER3_NV: number; // 0x8828
  const DRAW_BUFFER4_NV: number; // 0x8829
  const DRAW_BUFFER5_NV: number; // 0x882a
  const DRAW_BUFFER6_NV: number; // 0x882b
  const DRAW_BUFFER7_NV: number; // 0x882c
  const DRAW_BUFFER8_NV: number; // 0x882d
  const DRAW_BUFFER9_NV: number; // 0x882e
  const DRAW_BUFFER_EXT: number; // 0xc01
  const DRAW_FRAMEBUFFER_ANGLE: number; // 0x8ca9
  const DRAW_FRAMEBUFFER_APPLE: number; // 0x8ca9
  const DRAW_FRAMEBUFFER_BINDING_ANGLE: number; // 0x8ca6
  const DRAW_FRAMEBUFFER_BINDING_APPLE: number; // 0x8ca6
  const DRAW_FRAMEBUFFER_BINDING_NV: number; // 0x8ca6
  const DRAW_FRAMEBUFFER_NV: number; // 0x8ca9
  const DST_ALPHA: number; // 0x304
  const DST_COLOR: number; // 0x306
  const DYNAMIC_DRAW: number; // 0x88e8
  const ELEMENT_ARRAY_BUFFER: number; // 0x8893
  const ELEMENT_ARRAY_BUFFER_BINDING: number; // 0x8895
  const EQUAL: number; // 0x202
  const ES_VERSION_2_0: number; // 0x1
  const ETC1_RGB8_OES: number; // 0x8d64
  const ETC1_SRGB8_NV: number; // 0x88ee
  const EXTENSIONS: number; // 0x1f03
  const EXT_blend_minmax: number; // 0x1
  const EXT_color_buffer_half_float: number; // 0x1
  const EXT_debug_label: number; // 0x1
  const EXT_debug_marker: number; // 0x1
  const EXT_discard_framebuffer: number; // 0x1
  const EXT_map_buffer_range: number; // 0x1
  const EXT_multi_draw_arrays: number; // 0x1
  const EXT_multisampled_render_to_texture: number; // 0x1
  const EXT_multiview_draw_buffers: number; // 0x1
  const EXT_occlusion_query_boolean: number; // 0x1
  const EXT_read_format_bgra: number; // 0x1
  const EXT_robustness: number; // 0x1
  const EXT_sRGB: number; // 0x1
  const EXT_separate_shader_objects: number; // 0x1
  const EXT_shader_framebuffer_fetch: number; // 0x1
  const EXT_shader_texture_lod: number; // 0x1
  const EXT_shadow_samplers: number; // 0x1
  const EXT_texture_compression_dxt1: number; // 0x1
  const EXT_texture_filter_anisotropic: number; // 0x1
  const EXT_texture_format_BGRA8888: number; // 0x1
  const EXT_texture_rg: number; // 0x1
  const EXT_texture_storage: number; // 0x1
  const EXT_texture_type_2_10_10_10_REV: number; // 0x1
  const EXT_unpack_subimage: number; // 0x1
  const FALSE: number; // 0x0
  const FASTEST: number; // 0x1101
  const FENCE_CONDITION_NV: number; // 0x84f4
  const FENCE_STATUS_NV: number; // 0x84f3
  const FIXED: number; // 0x140c
  const FJ_shader_binary_GCCSO: number; // 0x1
  const FLOAT: number; // 0x1406
  const FLOAT_MAT2: number; // 0x8b5a
  const FLOAT_MAT3: number; // 0x8b5b
  const FLOAT_MAT4: number; // 0x8b5c
  const FLOAT_VEC2: number; // 0x8b50
  const FLOAT_VEC3: number; // 0x8b51
  const FLOAT_VEC4: number; // 0x8b52
  const FRAGMENT_SHADER: number; // 0x8b30
  const FRAGMENT_SHADER_BIT_EXT: number; // 0x2
  const FRAGMENT_SHADER_DERIVATIVE_HINT_OES: number; // 0x8b8b
  const FRAGMENT_SHADER_DISCARDS_SAMPLES_EXT: number; // 0x8a52
  const FRAMEBUFFER: number; // 0x8d40
  const FRAMEBUFFER_ATTACHMENT_ANGLE: number; // 0x93a3
  const FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING_EXT: number; // 0x8210
  const FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE_EXT: number; // 0x8211
  const FRAMEBUFFER_ATTACHMENT_OBJECT_NAME: number; // 0x8cd1
  const FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE: number; // 0x8cd0
  const FRAMEBUFFER_ATTACHMENT_TEXTURE_3D_ZOFFSET_OES: number; // 0x8cd4
  const FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE: number; // 0x8cd3
  const FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL: number; // 0x8cd2
  const FRAMEBUFFER_ATTACHMENT_TEXTURE_SAMPLES_EXT: number; // 0x8d6c
  const FRAMEBUFFER_BINDING: number; // 0x8ca6
  const FRAMEBUFFER_COMPLETE: number; // 0x8cd5
  const FRAMEBUFFER_INCOMPLETE_ATTACHMENT: number; // 0x8cd6
  const FRAMEBUFFER_INCOMPLETE_DIMENSIONS: number; // 0x8cd9
  const FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT: number; // 0x8cd7
  const FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_ANGLE: number; // 0x8d56
  const FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_APPLE: number; // 0x8d56
  const FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_EXT: number; // 0x8d56
  const FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_IMG: number; // 0x9134
  const FRAMEBUFFER_INCOMPLETE_MULTISAMPLE_NV: number; // 0x8d56
  const FRAMEBUFFER_UNDEFINED_OES: number; // 0x8219
  const FRAMEBUFFER_UNSUPPORTED: number; // 0x8cdd
  const FRONT: number; // 0x404
  const FRONT_AND_BACK: number; // 0x408
  const FRONT_FACE: number; // 0xb46
  const FUNC_ADD: number; // 0x8006
  const FUNC_REVERSE_SUBTRACT: number; // 0x800b
  const FUNC_SUBTRACT: number; // 0x800a
  const GENERATE_MIPMAP_HINT: number; // 0x8192
  const GEQUAL: number; // 0x206
  const GPU_OPTIMIZED_QCOM: number; // 0x8fb2
  const GREATER: number; // 0x204
  const GREEN_BITS: number; // 0xd53
  const GUILTY_CONTEXT_RESET_EXT: number; // 0x8253
  const HALF_FLOAT_OES: number; // 0x8d61
  const HIGH_FLOAT: number; // 0x8df2
  const HIGH_INT: number; // 0x8df5
  const IMG_multisampled_render_to_texture: number; // 0x1
  const IMG_program_binary: number; // 0x1
  const IMG_read_format: number; // 0x1
  const IMG_shader_binary: number; // 0x1
  const IMG_texture_compression_pvrtc: number; // 0x1
  const IMG_texture_compression_pvrtc2: number; // 0x1
  const IMPLEMENTATION_COLOR_READ_FORMAT: number; // 0x8b9b
  const IMPLEMENTATION_COLOR_READ_TYPE: number; // 0x8b9a
  const INCR: number; // 0x1e02
  const INCR_WRAP: number; // 0x8507
  const INFO_LOG_LENGTH: number; // 0x8b84
  const INNOCENT_CONTEXT_RESET_EXT: number; // 0x8254
  const INT: number; // 0x1404
  const INT_10_10_10_2_OES: number; // 0x8df7
  const INT_VEC2: number; // 0x8b53
  const INT_VEC3: number; // 0x8b54
  const INT_VEC4: number; // 0x8b55
  const INVALID_ENUM: number; // 0x500
  const INVALID_FRAMEBUFFER_OPERATION: number; // 0x506
  const INVALID_OPERATION: number; // 0x502
  const INVALID_VALUE: number; // 0x501
  const INVERT: number; // 0x150a
  const KEEP: number; // 0x1e00
  const KHR_debug: number; // 0x1
  const KHR_texture_compression_astc_ldr: number; // 0x1
  const LEQUAL: number; // 0x203
  const LESS: number; // 0x201
  const LINEAR: number; // 0x2601
  const LINEAR_MIPMAP_LINEAR: number; // 0x2703
  const LINEAR_MIPMAP_NEAREST: number; // 0x2701
  const LINES: number; // 0x1
  const LINE_LOOP: number; // 0x2
  const LINE_STRIP: number; // 0x3
  const LINE_WIDTH: number; // 0xb21
  const LINK_STATUS: number; // 0x8b82
  const LOSE_CONTEXT_ON_RESET_EXT: number; // 0x8252
  const LOW_FLOAT: number; // 0x8df0
  const LOW_INT: number; // 0x8df3
  const LUMINANCE: number; // 0x1909
  const LUMINANCE16F_EXT: number; // 0x881e
  const LUMINANCE32F_EXT: number; // 0x8818
  const LUMINANCE4_ALPHA4_OES: number; // 0x8043
  const LUMINANCE8_ALPHA8_EXT: number; // 0x8045
  const LUMINANCE8_ALPHA8_OES: number; // 0x8045
  const LUMINANCE8_EXT: number; // 0x8040
  const LUMINANCE8_OES: number; // 0x8040
  const LUMINANCE_ALPHA: number; // 0x190a
  const LUMINANCE_ALPHA16F_EXT: number; // 0x881f
  const LUMINANCE_ALPHA32F_EXT: number; // 0x8819
  const MALI_PROGRAM_BINARY_ARM: number; // 0x8f61
  const MALI_SHADER_BINARY_ARM: number; // 0x8f60
  const MAP_FLUSH_EXPLICIT_BIT_EXT: number; // 0x10
  const MAP_INVALIDATE_BUFFER_BIT_EXT: number; // 0x8
  const MAP_INVALIDATE_RANGE_BIT_EXT: number; // 0x4
  const MAP_READ_BIT_EXT: number; // 0x1
  const MAP_UNSYNCHRONIZED_BIT_EXT: number; // 0x20
  const MAP_WRITE_BIT_EXT: number; // 0x2
  const MAX_3D_TEXTURE_SIZE_OES: number; // 0x8073
  const MAX_COLOR_ATTACHMENTS_NV: number; // 0x8cdf
  const MAX_COMBINED_TEXTURE_IMAGE_UNITS: number; // 0x8b4d
  const MAX_CUBE_MAP_TEXTURE_SIZE: number; // 0x851c
  const MAX_DEBUG_GROUP_STACK_DEPTH: number; // 0x826c
  const MAX_DEBUG_LOGGED_MESSAGES: number; // 0x9144
  const MAX_DEBUG_MESSAGE_LENGTH: number; // 0x9143
  const MAX_DRAW_BUFFERS_NV: number; // 0x8824
  const MAX_EXT: number; // 0x8008
  const MAX_FRAGMENT_UNIFORM_VECTORS: number; // 0x8dfd
  const MAX_LABEL_LENGTH: number; // 0x82e8
  const MAX_MULTIVIEW_BUFFERS_EXT: number; // 0x90f2
  const MAX_RENDERBUFFER_SIZE: number; // 0x84e8
  const MAX_SAMPLES_ANGLE: number; // 0x8d57
  const MAX_SAMPLES_APPLE: number; // 0x8d57
  const MAX_SAMPLES_EXT: number; // 0x8d57
  const MAX_SAMPLES_IMG: number; // 0x9135
  const MAX_SAMPLES_NV: number; // 0x8d57
  const MAX_SERVER_WAIT_TIMEOUT_APPLE: number; // 0x9111
  const MAX_TEXTURE_IMAGE_UNITS: number; // 0x8872
  const MAX_TEXTURE_MAX_ANISOTROPY_EXT: number; // 0x84ff
  const MAX_TEXTURE_SIZE: number; // 0xd33
  const MAX_VARYING_VECTORS: number; // 0x8dfc
  const MAX_VERTEX_ATTRIBS: number; // 0x8869
  const MAX_VERTEX_TEXTURE_IMAGE_UNITS: number; // 0x8b4c
  const MAX_VERTEX_UNIFORM_VECTORS: number; // 0x8dfb
  const MAX_VIEWPORT_DIMS: number; // 0xd3a
  const MEDIUM_FLOAT: number; // 0x8df1
  const MEDIUM_INT: number; // 0x8df4
  const MIN_EXT: number; // 0x8007
  const MIRRORED_REPEAT: number; // 0x8370
  const MULTISAMPLE_BUFFER_BIT0_QCOM: number; // 0x1000000
  const MULTISAMPLE_BUFFER_BIT1_QCOM: number; // 0x2000000
  const MULTISAMPLE_BUFFER_BIT2_QCOM: number; // 0x4000000
  const MULTISAMPLE_BUFFER_BIT3_QCOM: number; // 0x8000000
  const MULTISAMPLE_BUFFER_BIT4_QCOM: number; // 0x10000000
  const MULTISAMPLE_BUFFER_BIT5_QCOM: number; // 0x20000000
  const MULTISAMPLE_BUFFER_BIT6_QCOM: number; // 0x40000000
  const MULTISAMPLE_BUFFER_BIT7_QCOM: number; // 0x80000000
  const MULTIVIEW_EXT: number; // 0x90f1
  const NEAREST: number; // 0x2600
  const NEAREST_MIPMAP_LINEAR: number; // 0x2702
  const NEAREST_MIPMAP_NEAREST: number; // 0x2700
  const NEVER: number; // 0x200
  const NICEST: number; // 0x1102
  const NONE: number; // 0x0
  const NOTEQUAL: number; // 0x205
  const NO_ERROR: number; // 0x0
  const NO_RESET_NOTIFICATION_EXT: number; // 0x8261
  const NUM_COMPRESSED_TEXTURE_FORMATS: number; // 0x86a2
  const NUM_PROGRAM_BINARY_FORMATS_OES: number; // 0x87fe
  const NUM_SHADER_BINARY_FORMATS: number; // 0x8df9
  const NV_coverage_sample: number; // 0x1
  const NV_depth_nonlinear: number; // 0x1
  const NV_draw_buffers: number; // 0x1
  const NV_draw_instanced: number; // 0x1
  const NV_fbo_color_attachments: number; // 0x1
  const NV_fence: number; // 0x1
  const NV_framebuffer_blit: number; // 0x1
  const NV_framebuffer_multisample: number; // 0x1
  const NV_generate_mipmap_sRGB: number; // 0x1
  const NV_instanced_arrays: number; // 0x1
  const NV_read_buffer: number; // 0x1
  const NV_read_buffer_front: number; // 0x1
  const NV_read_depth: number; // 0x1
  const NV_read_depth_stencil: number; // 0x1
  const NV_read_stencil: number; // 0x1
  const NV_sRGB_formats: number; // 0x1
  const NV_shadow_samplers_array: number; // 0x1
  const NV_shadow_samplers_cube: number; // 0x1
  const NV_texture_border_clamp: number; // 0x1
  const NV_texture_compression_s3tc_update: number; // 0x1
  const NV_texture_npot_2D_mipmap: number; // 0x1
  const OBJECT_TYPE_APPLE: number; // 0x9112
  const OES_EGL_image: number; // 0x1
  const OES_EGL_image_external: number; // 0x1
  const OES_compressed_ETC1_RGB8_texture: number; // 0x1
  const OES_compressed_paletted_texture: number; // 0x1
  const OES_depth24: number; // 0x1
  const OES_depth32: number; // 0x1
  const OES_depth_texture: number; // 0x1
  const OES_element_index_uint: number; // 0x1
  const OES_fbo_render_mipmap: number; // 0x1
  const OES_fragment_precision_high: number; // 0x1
  const OES_get_program_binary: number; // 0x1
  const OES_mapbuffer: number; // 0x1
  const OES_packed_depth_stencil: number; // 0x1
  const OES_required_internalformat: number; // 0x1
  const OES_rgb8_rgba8: number; // 0x1
  const OES_standard_derivatives: number; // 0x1
  const OES_stencil1: number; // 0x1
  const OES_stencil4: number; // 0x1
  const OES_surfaceless_context: number; // 0x1
  const OES_texture_3D: number; // 0x1
  const OES_texture_float: number; // 0x1
  const OES_texture_float_linear: number; // 0x1
  const OES_texture_half_float: number; // 0x1
  const OES_texture_half_float_linear: number; // 0x1
  const OES_texture_npot: number; // 0x1
  const OES_vertex_array_object: number; // 0x1
  const OES_vertex_half_float: number; // 0x1
  const OES_vertex_type_10_10_10_2: number; // 0x1
  const ONE: number; // 0x1
  const ONE_MINUS_CONSTANT_ALPHA: number; // 0x8004
  const ONE_MINUS_CONSTANT_COLOR: number; // 0x8002
  const ONE_MINUS_DST_ALPHA: number; // 0x305
  const ONE_MINUS_DST_COLOR: number; // 0x307
  const ONE_MINUS_SRC_ALPHA: number; // 0x303
  const ONE_MINUS_SRC_COLOR: number; // 0x301
  const OUT_OF_MEMORY: number; // 0x505
  const PACK_ALIGNMENT: number; // 0xd05
  const PACK_REVERSE_ROW_ORDER_ANGLE: number; // 0x93a4
  const PALETTE4_R5_G6_B5_OES: number; // 0x8b92
  const PALETTE4_RGB5_A1_OES: number; // 0x8b94
  const PALETTE4_RGB8_OES: number; // 0x8b90
  const PALETTE4_RGBA4_OES: number; // 0x8b93
  const PALETTE4_RGBA8_OES: number; // 0x8b91
  const PALETTE8_R5_G6_B5_OES: number; // 0x8b97
  const PALETTE8_RGB5_A1_OES: number; // 0x8b99
  const PALETTE8_RGB8_OES: number; // 0x8b95
  const PALETTE8_RGBA4_OES: number; // 0x8b98
  const PALETTE8_RGBA8_OES: number; // 0x8b96
  const PERCENTAGE_AMD: number; // 0x8bc3
  const PERFMON_GLOBAL_MODE_QCOM: number; // 0x8fa0
  const PERFMON_RESULT_AMD: number; // 0x8bc6
  const PERFMON_RESULT_AVAILABLE_AMD: number; // 0x8bc4
  const PERFMON_RESULT_SIZE_AMD: number; // 0x8bc5
  const POINTS: number; // 0x0
  const POLYGON_OFFSET_FACTOR: number; // 0x8038
  const POLYGON_OFFSET_FILL: number; // 0x8037
  const POLYGON_OFFSET_UNITS: number; // 0x2a00
  const PROGRAM: number; // 0x82e2
  const PROGRAM_BINARY_ANGLE: number; // 0x93a6
  const PROGRAM_BINARY_FORMATS_OES: number; // 0x87ff
  const PROGRAM_BINARY_LENGTH_OES: number; // 0x8741
  const PROGRAM_OBJECT_EXT: number; // 0x8b40
  const PROGRAM_PIPELINE_BINDING_EXT: number; // 0x825a
  const PROGRAM_PIPELINE_OBJECT_EXT: number; // 0x8a4f
  const PROGRAM_SEPARABLE_EXT: number; // 0x8258
  const QCOM_alpha_test: number; // 0x1
  const QCOM_binning_control: number; // 0x1
  const QCOM_driver_control: number; // 0x1
  const QCOM_extended_get: number; // 0x1
  const QCOM_extended_get2: number; // 0x1
  const QCOM_perfmon_global_mode: number; // 0x1
  const QCOM_tiled_rendering: number; // 0x1
  const QCOM_writeonly_rendering: number; // 0x1
  const QUERY: number; // 0x82e3
  const QUERY_OBJECT_EXT: number; // 0x9153
  const QUERY_RESULT_AVAILABLE_EXT: number; // 0x8867
  const QUERY_RESULT_EXT: number; // 0x8866
  const R16F_EXT: number; // 0x822d
  const R32F_EXT: number; // 0x822e
  const R8_EXT: number; // 0x8229
  const READ_BUFFER_EXT: number; // 0xc02
  const READ_BUFFER_NV: number; // 0xc02
  const READ_FRAMEBUFFER_ANGLE: number; // 0x8ca8
  const READ_FRAMEBUFFER_APPLE: number; // 0x8ca8
  const READ_FRAMEBUFFER_BINDING_ANGLE: number; // 0x8caa
  const READ_FRAMEBUFFER_BINDING_APPLE: number; // 0x8caa
  const READ_FRAMEBUFFER_BINDING_NV: number; // 0x8caa
  const READ_FRAMEBUFFER_NV: number; // 0x8ca8
  const RED_BITS: number; // 0xd52
  const RED_EXT: number; // 0x1903
  const RENDERBUFFER: number; // 0x8d41
  const RENDERBUFFER_ALPHA_SIZE: number; // 0x8d53
  const RENDERBUFFER_BINDING: number; // 0x8ca7
  const RENDERBUFFER_BLUE_SIZE: number; // 0x8d52
  const RENDERBUFFER_DEPTH_SIZE: number; // 0x8d54
  const RENDERBUFFER_GREEN_SIZE: number; // 0x8d51
  const RENDERBUFFER_HEIGHT: number; // 0x8d43
  const RENDERBUFFER_INTERNAL_FORMAT: number; // 0x8d44
  const RENDERBUFFER_RED_SIZE: number; // 0x8d50
  const RENDERBUFFER_SAMPLES_ANGLE: number; // 0x8cab
  const RENDERBUFFER_SAMPLES_APPLE: number; // 0x8cab
  const RENDERBUFFER_SAMPLES_EXT: number; // 0x8cab
  const RENDERBUFFER_SAMPLES_IMG: number; // 0x9133
  const RENDERBUFFER_SAMPLES_NV: number; // 0x8cab
  const RENDERBUFFER_STENCIL_SIZE: number; // 0x8d55
  const RENDERBUFFER_WIDTH: number; // 0x8d42
  const RENDERER: number; // 0x1f01
  const RENDER_DIRECT_TO_FRAMEBUFFER_QCOM: number; // 0x8fb3
  const REPEAT: number; // 0x2901
  const REPLACE: number; // 0x1e01
  const REQUIRED_TEXTURE_IMAGE_UNITS_OES: number; // 0x8d68
  const RESET_NOTIFICATION_STRATEGY_EXT: number; // 0x8256
  const RG16F_EXT: number; // 0x822f
  const RG32F_EXT: number; // 0x8230
  const RG8_EXT: number; // 0x822b
  const RGB: number; // 0x1907
  const RGB10_A2_EXT: number; // 0x8059
  const RGB10_EXT: number; // 0x8052
  const RGB16F_EXT: number; // 0x881b
  const RGB32F_EXT: number; // 0x8815
  const RGB565: number; // 0x8d62
  const RGB565_OES: number; // 0x8d62
  const RGB5_A1: number; // 0x8057
  const RGB5_A1_OES: number; // 0x8057
  const RGB8_OES: number; // 0x8051
  const RGBA: number; // 0x1908
  const RGBA16F_EXT: number; // 0x881a
  const RGBA32F_EXT: number; // 0x8814
  const RGBA4: number; // 0x8056
  const RGBA4_OES: number; // 0x8056
  const RGBA8_OES: number; // 0x8058
  const RGB_422_APPLE: number; // 0x8a1f
  const RG_EXT: number; // 0x8227
  const SAMPLER: number; // 0x82e6
  const SAMPLER_2D: number; // 0x8b5e
  const SAMPLER_2D_ARRAY_SHADOW_NV: number; // 0x8dc4
  const SAMPLER_2D_SHADOW_EXT: number; // 0x8b62
  const SAMPLER_3D_OES: number; // 0x8b5f
  const SAMPLER_CUBE: number; // 0x8b60
  const SAMPLER_CUBE_SHADOW_NV: number; // 0x8dc5
  const SAMPLER_EXTERNAL_OES: number; // 0x8d66
  const SAMPLES: number; // 0x80a9
  const SAMPLE_ALPHA_TO_COVERAGE: number; // 0x809e
  const SAMPLE_BUFFERS: number; // 0x80a8
  const SAMPLE_COVERAGE: number; // 0x80a0
  const SAMPLE_COVERAGE_INVERT: number; // 0x80ab
  const SAMPLE_COVERAGE_VALUE: number; // 0x80aa
  const SCISSOR_BOX: number; // 0xc10
  const SCISSOR_TEST: number; // 0xc11
  const SGX_BINARY_IMG: number; // 0x8c0a
  const SGX_PROGRAM_BINARY_IMG: number; // 0x9130
  const SHADER: number; // 0x82e1
  const SHADER_BINARY_DMP: number; // 0x9250
  const SHADER_BINARY_FORMATS: number; // 0x8df8
  const SHADER_BINARY_VIV: number; // 0x8fc4
  const SHADER_COMPILER: number; // 0x8dfa
  const SHADER_OBJECT_EXT: number; // 0x8b48
  const SHADER_SOURCE_LENGTH: number; // 0x8b88
  const SHADER_TYPE: number; // 0x8b4f
  const SHADING_LANGUAGE_VERSION: number; // 0x8b8c
  const SHORT: number; // 0x1402
  const SIGNALED_APPLE: number; // 0x9119
  const SLUMINANCE8_ALPHA8_NV: number; // 0x8c45
  const SLUMINANCE8_NV: number; // 0x8c47
  const SLUMINANCE_ALPHA_NV: number; // 0x8c44
  const SLUMINANCE_NV: number; // 0x8c46
  const SRC_ALPHA: number; // 0x302
  const SRC_ALPHA_SATURATE: number; // 0x308
  const SRC_COLOR: number; // 0x300
  const SRGB8_ALPHA8_EXT: number; // 0x8c43
  const SRGB8_NV: number; // 0x8c41
  const SRGB_ALPHA_EXT: number; // 0x8c42
  const SRGB_EXT: number; // 0x8c40
  const STACK_OVERFLOW: number; // 0x503
  const STACK_UNDERFLOW: number; // 0x504
  const STATE_RESTORE: number; // 0x8bdc
  const STATIC_DRAW: number; // 0x88e4
  const STENCIL_ATTACHMENT: number; // 0x8d20
  const STENCIL_BACK_FAIL: number; // 0x8801
  const STENCIL_BACK_FUNC: number; // 0x8800
  const STENCIL_BACK_PASS_DEPTH_FAIL: number; // 0x8802
  const STENCIL_BACK_PASS_DEPTH_PASS: number; // 0x8803
  const STENCIL_BACK_REF: number; // 0x8ca3
  const STENCIL_BACK_VALUE_MASK: number; // 0x8ca4
  const STENCIL_BACK_WRITEMASK: number; // 0x8ca5
  const STENCIL_BITS: number; // 0xd57
  const STENCIL_BUFFER_BIT: number; // 0x400
  const STENCIL_BUFFER_BIT0_QCOM: number; // 0x10000
  const STENCIL_BUFFER_BIT1_QCOM: number; // 0x20000
  const STENCIL_BUFFER_BIT2_QCOM: number; // 0x40000
  const STENCIL_BUFFER_BIT3_QCOM: number; // 0x80000
  const STENCIL_BUFFER_BIT4_QCOM: number; // 0x100000
  const STENCIL_BUFFER_BIT5_QCOM: number; // 0x200000
  const STENCIL_BUFFER_BIT6_QCOM: number; // 0x400000
  const STENCIL_BUFFER_BIT7_QCOM: number; // 0x800000
  const STENCIL_CLEAR_VALUE: number; // 0xb91
  const STENCIL_EXT: number; // 0x1802
  const STENCIL_FAIL: number; // 0xb94
  const STENCIL_FUNC: number; // 0xb92
  const STENCIL_INDEX1_OES: number; // 0x8d46
  const STENCIL_INDEX4_OES: number; // 0x8d47
  const STENCIL_INDEX8: number; // 0x8d48
  const STENCIL_PASS_DEPTH_FAIL: number; // 0xb95
  const STENCIL_PASS_DEPTH_PASS: number; // 0xb96
  const STENCIL_REF: number; // 0xb97
  const STENCIL_TEST: number; // 0xb90
  const STENCIL_VALUE_MASK: number; // 0xb93
  const STENCIL_WRITEMASK: number; // 0xb98
  const STREAM_DRAW: number; // 0x88e0
  const SUBPIXEL_BITS: number; // 0xd50
  const SYNC_CONDITION_APPLE: number; // 0x9113
  const SYNC_FENCE_APPLE: number; // 0x9116
  const SYNC_FLAGS_APPLE: number; // 0x9115
  const SYNC_FLUSH_COMMANDS_BIT_APPLE: number; // 0x1
  const SYNC_GPU_COMMANDS_COMPLETE_APPLE: number; // 0x9117
  const SYNC_OBJECT_APPLE: number; // 0x8a53
  const SYNC_STATUS_APPLE: number; // 0x9114
  const TEXTURE: number; // 0x1702
  const TEXTURE0: number; // 0x84c0
  const TEXTURE1: number; // 0x84c1
  const TEXTURE10: number; // 0x84ca
  const TEXTURE11: number; // 0x84cb
  const TEXTURE12: number; // 0x84cc
  const TEXTURE13: number; // 0x84cd
  const TEXTURE14: number; // 0x84ce
  const TEXTURE15: number; // 0x84cf
  const TEXTURE16: number; // 0x84d0
  const TEXTURE17: number; // 0x84d1
  const TEXTURE18: number; // 0x84d2
  const TEXTURE19: number; // 0x84d3
  const TEXTURE2: number; // 0x84c2
  const TEXTURE20: number; // 0x84d4
  const TEXTURE21: number; // 0x84d5
  const TEXTURE22: number; // 0x84d6
  const TEXTURE23: number; // 0x84d7
  const TEXTURE24: number; // 0x84d8
  const TEXTURE25: number; // 0x84d9
  const TEXTURE26: number; // 0x84da
  const TEXTURE27: number; // 0x84db
  const TEXTURE28: number; // 0x84dc
  const TEXTURE29: number; // 0x84dd
  const TEXTURE3: number; // 0x84c3
  const TEXTURE30: number; // 0x84de
  const TEXTURE31: number; // 0x84df
  const TEXTURE4: number; // 0x84c4
  const TEXTURE5: number; // 0x84c5
  const TEXTURE6: number; // 0x84c6
  const TEXTURE7: number; // 0x84c7
  const TEXTURE8: number; // 0x84c8
  const TEXTURE9: number; // 0x84c9
  const TEXTURE_2D: number; // 0xde1
  const TEXTURE_3D_OES: number; // 0x806f
  const TEXTURE_BINDING_2D: number; // 0x8069
  const TEXTURE_BINDING_3D_OES: number; // 0x806a
  const TEXTURE_BINDING_CUBE_MAP: number; // 0x8514
  const TEXTURE_BINDING_EXTERNAL_OES: number; // 0x8d67
  const TEXTURE_BORDER_COLOR_NV: number; // 0x1004
  const TEXTURE_COMPARE_FUNC_EXT: number; // 0x884d
  const TEXTURE_COMPARE_MODE_EXT: number; // 0x884c
  const TEXTURE_CUBE_MAP: number; // 0x8513
  const TEXTURE_CUBE_MAP_NEGATIVE_X: number; // 0x8516
  const TEXTURE_CUBE_MAP_NEGATIVE_Y: number; // 0x8518
  const TEXTURE_CUBE_MAP_NEGATIVE_Z: number; // 0x851a
  const TEXTURE_CUBE_MAP_POSITIVE_X: number; // 0x8515
  const TEXTURE_CUBE_MAP_POSITIVE_Y: number; // 0x8517
  const TEXTURE_CUBE_MAP_POSITIVE_Z: number; // 0x8519
  const TEXTURE_DEPTH_QCOM: number; // 0x8bd4
  const TEXTURE_EXTERNAL_OES: number; // 0x8d65
  const TEXTURE_FORMAT_QCOM: number; // 0x8bd6
  const TEXTURE_HEIGHT_QCOM: number; // 0x8bd3
  const TEXTURE_IMAGE_VALID_QCOM: number; // 0x8bd8
  const TEXTURE_IMMUTABLE_FORMAT_EXT: number; // 0x912f
  const TEXTURE_INTERNAL_FORMAT_QCOM: number; // 0x8bd5
  const TEXTURE_MAG_FILTER: number; // 0x2800
  const TEXTURE_MAX_ANISOTROPY_EXT: number; // 0x84fe
  const TEXTURE_MAX_LEVEL_APPLE: number; // 0x813d
  const TEXTURE_MIN_FILTER: number; // 0x2801
  const TEXTURE_NUM_LEVELS_QCOM: number; // 0x8bd9
  const TEXTURE_OBJECT_VALID_QCOM: number; // 0x8bdb
  const TEXTURE_SAMPLES_IMG: number; // 0x9136
  const TEXTURE_TARGET_QCOM: number; // 0x8bda
  const TEXTURE_TYPE_QCOM: number; // 0x8bd7
  const TEXTURE_USAGE_ANGLE: number; // 0x93a2
  const TEXTURE_WIDTH_QCOM: number; // 0x8bd2
  const TEXTURE_WRAP_R_OES: number; // 0x8072
  const TEXTURE_WRAP_S: number; // 0x2802
  const TEXTURE_WRAP_T: number; // 0x2803
  const TIMEOUT_EXPIRED_APPLE: number; // 0x911b
  const TIMEOUT_IGNORED_APPLE: number; // 0xffffffffffffffff
  const TRANSLATED_SHADER_SOURCE_LENGTH_ANGLE: number; // 0x93a0
  const TRIANGLES: number; // 0x4
  const TRIANGLE_FAN: number; // 0x6
  const TRIANGLE_STRIP: number; // 0x5
  const TRUE: number; // 0x1
  const UNKNOWN_CONTEXT_RESET_EXT: number; // 0x8255
  const UNPACK_ALIGNMENT: number; // 0xcf5
  const UNPACK_ROW_LENGTH: number; // 0xcf2
  const UNPACK_SKIP_PIXELS: number; // 0xcf4
  const UNPACK_SKIP_ROWS: number; // 0xcf3
  const UNSIGNALED_APPLE: number; // 0x9118
  const UNSIGNED_BYTE: number; // 0x1401
  const UNSIGNED_INT: number; // 0x1405
  const UNSIGNED_INT64_AMD: number; // 0x8bc2
  const UNSIGNED_INT_10_10_10_2_OES: number; // 0x8df6
  const UNSIGNED_INT_24_8_OES: number; // 0x84fa
  const UNSIGNED_INT_2_10_10_10_REV_EXT: number; // 0x8368
  const UNSIGNED_NORMALIZED_EXT: number; // 0x8c17
  const UNSIGNED_SHORT: number; // 0x1403
  const UNSIGNED_SHORT_1_5_5_5_REV_EXT: number; // 0x8366
  const UNSIGNED_SHORT_4_4_4_4: number; // 0x8033
  const UNSIGNED_SHORT_4_4_4_4_REV_EXT: number; // 0x8365
  const UNSIGNED_SHORT_4_4_4_4_REV_IMG: number; // 0x8365
  const UNSIGNED_SHORT_5_5_5_1: number; // 0x8034
  const UNSIGNED_SHORT_5_6_5: number; // 0x8363
  const UNSIGNED_SHORT_8_8_APPLE: number; // 0x85ba
  const UNSIGNED_SHORT_8_8_REV_APPLE: number; // 0x85bb
  const VALIDATE_STATUS: number; // 0x8b83
  const VENDOR: number; // 0x1f00
  const VERSION: number; // 0x1f02
  const VERTEX_ARRAY_BINDING_OES: number; // 0x85b5
  const VERTEX_ARRAY_OBJECT_EXT: number; // 0x9154
  const VERTEX_ATTRIB_ARRAY_BUFFER_BINDING: number; // 0x889f
  const VERTEX_ATTRIB_ARRAY_DIVISOR_ANGLE: number; // 0x88fe
  const VERTEX_ATTRIB_ARRAY_DIVISOR_NV: number; // 0x88fe
  const VERTEX_ATTRIB_ARRAY_ENABLED: number; // 0x8622
  const VERTEX_ATTRIB_ARRAY_NORMALIZED: number; // 0x886a
  const VERTEX_ATTRIB_ARRAY_POINTER: number; // 0x8645
  const VERTEX_ATTRIB_ARRAY_SIZE: number; // 0x8623
  const VERTEX_ATTRIB_ARRAY_STRIDE: number; // 0x8624
  const VERTEX_ATTRIB_ARRAY_TYPE: number; // 0x8625
  const VERTEX_SHADER: number; // 0x8b31
  const VERTEX_SHADER_BIT_EXT: number; // 0x1
  const VIEWPORT: number; // 0xba2
  const VIV_shader_binary: number; // 0x1
  const WAIT_FAILED_APPLE: number; // 0x911d
  const WRITEONLY_RENDERING_QCOM: number; // 0x8823
  const WRITE_ONLY_OES: number; // 0x88b9
  const Z400_BINARY_AMD: number; // 0x8740
  const ZERO: number; // 0x0
  const VERTEX_ATTRIB_POINTER_VEC3: number; // 0
  const VERTEX_ATTRIB_POINTER_COLOR4B: number; // 1
}
